version: "3.5"
services:
  postgres:
    image: postgis/postgis:15-master
    restart: always
    ports:
      - '5454:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: data
    volumes:
      - ./data:/var/lib/postgresql/data
